{% set name = "RNAformer" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/57/19/1fc85e4b301f39994f6f7e14657e856a6e2efd200f484eeed0e0e5e2e2b0/rnaformer-0.0.1.tar.gz
  sha256: 36374aa476ffd0be681e8ad29fec64cb074b6e341db1dc8179fcbd43cdf5da55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - pytorch 
    - torchvision
    - tqdm 
    - pyyaml 
    - pyaml 
    - numpy 
    - packaging
    - wheel 
    - tabulate 
    - scipy 
    - pandas ==2.0.2
    - scikit-learn ==1.3.0
    - matplotlib-base ==3.7.2
    - polars
    - loralib ==0.1.2
    - tensorboard ==2.13.0
    - transformers 
    - datasets ==2.13.1
    - pytorch-lightning ==2.0.4
    - deepspeed ==0.9.5
    - rotary-embedding-torch 

test:
  imports:
    - RNAformer

about:
  home: https://github.com/automl/RNAformer 
  summary: 'RNAformer: a simple single-sequence-based deep learning model for RNA secondary structure prediction.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivelet
