{% set name = "RNAformer" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/40/ef/c4423512ea51c052d9ffd38c011390d70e6028fcb0c5e881a4ca706dffcc/rnaformer-1.3.2.tar.gz
  sha256: 112625f8cbc0a9f01b1fd00003967a068c5c25c8b4497733ccb5f812ac57e6a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - pytorch ==2.3.0
    - torchvision ==0.18.0
    - tqdm ==4.66.4
    - pyyaml ==6.0.1
    - pyaml ==24.4.0
    - numpy ==1.26.4
    - packaging ==24.0
    - wheel ==0.43.0
    - tabulate ==0.9.0
    - scipy ==1.13.0
    - pandas ==2.0.2
    - scikit-learn ==1.3.0
    - matplotlib-base ==3.7.2
    - polars ==0.20.26
    - loralib ==0.1.2
    - tensorboard ==2.13.0
    - transformers ==4.40.2
    - datasets ==2.13.1
    - pytorch-lightning ==2.0.4
    - deepspeed ==0.9.5
    - rotary-embedding-torch ==0.5.3

test:
  imports:
    - RNAformer

about:
  home: https://github.com/automl/RNAformer 
  summary: 'RNAformer: a simple single-sequence-based deep learning model for RNA secondary structure prediction.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivelet
