{% set name = "RNAformer" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/51/35/da09bc61ebc39bc674911a883f7636c3e99e10fe3b4c2de06a99ef6de0e1/rnaformer-1.2.0.tar.gz
  sha256: 4474af2e142b32238f5bc69951807d0eae4b570c3e4d3a02edc25692f149f4c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10

test:
  imports:
    - RNAformer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/RNAformer 
  summary: 'RNAformer: a simple single-sequence-based deep learning model for RNA secondary structure prediction.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivelet
