{% set name = "RNAformer" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/11/f6/162d97ca73a28c843a2606a09974ead8410be8b3bc913ba7ec0f9a7960b0/rnaformer-1.3.1.tar.gz
  sha256: 7b85f93bfbc1997e1650bc525a78c7df7a6a0b70d64848379357963f4e6d3671

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - pytorch
    - torchvision
    - tqdm
    - pyyaml
    - pyaml
    - numpy
    - packaging
    - wheel
    - tabulate
    - scipy
    - pandas ==2.0.2
    - scikit-learn ==1.3.0
    - matplotlib ==3.7.2
    - polars
    - loralib ==0.1.2
    - tensorboard ==2.13.0
    - transformers
    - datasets ==2.13.1
    - pytorch-lightning ==2.0.4
    - deepspeed ==0.9.5
    - rotary-embedding-torch

test:
  imports:
    - RNAformer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/RNAformer 
  summary: 'RNAformer: a simple single-sequence-based deep learning model for RNA secondary structure prediction.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivelet
