{% set name = "RNAformer" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/51/35/da09bc61ebc39bc674911a883f7636c3e99e10fe3b4c2de06a99ef6de0e1/rnaformer-1.2.0.tar.gz
  sha256: 4474af2e142b32238f5bc69951807d0eae4b570c3e4d3a02edc25692f149f4c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - torch ==2.1.2
    - loralib ==0.1.2
    - torchvision ==0.16.1
    - tqdm ==4.66.2
    - numpy ==1.26.4
    - einops ==0.7.0
    - pytorch-lightning ==2.2.2
    - packaging ==24.0
    - wheel ==0.43.0
    - tabulate ==0.9.0
    - scipy ==1.13.0
    - pandas ==2.2.2
    - scikit-learn ==1.4.2
    - matplotlib ==3.8.4
    - polars ==0.20.21
    - tensorboard ==2.16.2
    - transformers ==4.39.3
    - datasets ==2.18.0
    - deepspeed ==0.14.0
    - rotary-embedding-torch ==0.5.3

test:
  imports:
    - RNAformer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/automl/RNAformer 
  summary: 'RNAformer: a simple single-sequence-based deep learning model for RNA secondary structure prediction.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivelet
